http:
  port: "8081"
  listener:
    host: "0.0.0.0"
    port: "8081"

user:
  host: "s-test-lbulnesjimenez-3dmtql.5sc6y6-1.usa-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
api:
  id: "20322253"
  
prc-test:
  auth:
    client_id: "![lmYHLCTKxq9x7WepdsoXLcWIVnh8yrTou7FUtxfPgVguAGUGYfPT7g==]"
    client_secret: "![06qtJkERoRbaTsPmIpvmScAWF5Qsh8QuwOD+FZ4OvvniZZCJEQyUkQ==]"